### ISSUE TITLE
Trying to install on AWS.

### ISSUE THREAD

**Issue by Scramasax** [kiswa/TaskBoard#359] opened 2017-05-23 07:45 UTC
ubuntu@ip-xxx-xx-xx-xx:/var/www/html/TaskBoard-master$ ./build/build-all
Building...
Installing dependencies
./build/build-all: line 10: ./build/composer.phar: Permission denied

**Comment by kiswa** [comment] 2017-05-23 14:13
Duplicate of #358

**Closed by kiswa** 2017-05-23 14:13 UTC
