### ISSUE TITLE
Duplicate board

### ISSUE THREAD

**Issue by nikosgonmare** [kiswa/TaskBoard#570] opened 2020-11-21 22:05 UTC
**Is your feature request related to a problem? Please describe.**
I create a new standard board for each Trustee meeting of a charity I help run.  These are always identical in their settings for columns and categories. Currently I set them up each month and then set up similar tasks within the columns for each meeting. This can take a bit of time.  

**Describe the solution you'd like**
When creating a Board it would be good to duplicate a previously made Board template 

**Describe alternatives you've considered**
**Additional context**

**Comment by kiswa** [comment] 2020-11-30 14:24
Duplicate of #417, if I'm not mistaken.

**Closed by kiswa** 2020-11-30 14:24 UTC
