### ISSUE TITLE
Easy adding links, files, images, etc.

### ISSUE THREAD

**Issue by torwag** [kiswa/TaskBoard#160] opened 2015-04-12 12:08 UTC
Hi,
after starting using taskboard, I figured out that I miss a bit the documentation part for a particular task.
At the moment I can add a comment and this comment can contain a link or a other markup.
Furthermore, I can add files.
This all appears in a comment like thread.

I would love to see more possibilities e.g. being able to easily add images (thumbnail inline images), easy way to add links, movies (inline player), audio (inline player), and being able to open files with certain mime types e.g. txt, pdf, odt, doc, etc.

Or in other words, I would love if Taskboard would have a bit more documentation capabilities.
That would allow me to collect all kind of various information to a task and hence by time get all the infos needed to finalize it.
I think the markdown capable Description filed is capable of supporting many of the above features. However, it could be made easier to add multimedia data, e.g.,  adding a toolbar above the  Description field. Furthermore, a file-view to see all attached files could be useful.

**Comment by torwag** [comment] 2015-04-15 15:40
I checked there are several Markdown Tookbars. 
Would it be a good start to add one of those to the Description field? Some have pop ups to select images, thus people could easily add pictures to a task. 
Other then this I would love to have a bit more file manipulation options... like adding, deleting files, file view, sort files, etc..

**Comment by kiswa** [comment] 2015-04-15 16:39
Within the description itself? No. I want it to be kept clean and simple.

If a task/item needs files, there is an "Attachments" section just for that, which does all that (except sorting).

That said, if you want to fork TaskBoard and make your own version that does all that in the description, by all means go for it! I just don't see it being something in the TaskBoard I created.

**Comment by kiswa** [comment] 2015-04-15 16:42
Upon further review, this feels like a duplicate of #62. I want TaskBoard to be fairly minimal on the display side of things.

**Closed by kiswa** 2015-04-15 16:42 UTC
Labels: duplicate
