### ISSUE TITLE
Cannot login via Internet while logging in in local network works.

### ISSUE THREAD

**Issue by trephis** [kiswa/TaskBoard#307] opened 2016-08-31 21:27 UTC
I installed TaskBoard (on my Raspberry Pi running Raspbian) as described here: https://github.com/kiswa/TaskBoard/blob/master/README.md#install.
When I login via hostname in the local network everything is fine. But when trying to login via domain name over the internet I get the following error:

POST http://MYDOMAINNAME/TaskBoard/api/login 404 (Not Found)(anonymous function) @ angular.js:9866sendReq @ angular.js:9667serverRequest @ angular.js:9383processQueue @ angular.js:13248(anonymous function) @ angular.js:13264$eval @ angular.js:14466$digest @ angular.js:14282$apply @ angular.js:14571(anonymous function) @ angular.js:21571dispatch @ jquery-1.11.3.min.js:4r.handle @ jquery-1.11.3.min.js:4
angular.js:11655 

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at fromJson (http://MYDOMAINNAME/TaskBoard/lib/angular.js:1072:14)
    at defaultHttpResponseTransform (http://MYDOMAINNAME/TaskBoard/lib/angular.js:8618:16)
    at http://MYDOMAINNAME/TaskBoard/lib/angular.js:8703:12
    at forEach (http://MYDOMAINNAME/TaskBoard/lib/angular.js:323:20)
    at transformData (http://MYDOMAINNAME/TaskBoard/lib/angular.js:8702:3)
    at transformResponse (http://MYDOMAINNAME/TaskBoard/lib/angular.js:9428:23)
    at processQueue (http://MYDOMAINNAME/TaskBoard/lib/angular.js:13248:27)
    at http://MYDOMAINNAME/TaskBoard/lib/angular.js:13264:27
    at Scope.$eval (http://MYDOMAINNAME/TaskBoard/lib/angular.js:14466:28)(anonymous function) @ angular.js:11655(anonymous function) @ angular.js:8596processQueue @ angular.js:13256(anonymous function) @ angular.js:13264$eval @ angular.js:14466$digest @ angular.js:14282$apply @ angular.js:14571done @ angular.js:9698completeRequest @ angular.js:9888requestLoaded @ angular.js:9829
angular.js:11655 

TypeError: Cannot read property 'message' of undefined
    at login.js:31
    at angular.js:9415
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$eval (angular.js:14466)
    at Scope.$digest (angular.js:14282)
    at Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at XMLHttpRequest.requestLoaded (angular.js:9829)

Thank you in advance.

**Comment by kiswa** [comment] 2016-09-01 19:12
Take a look the the Preview or Response tabs for that request and let me know what's coming back. The fact that it said "Unexpected token < in JSON" means it's probably getting an HTML document (which is likely a server configuration issue).

**Comment by trephis** [comment] 2016-09-02 10:41
![bildschirmfoto vom 2016-09-02 12 35 17](https://cloud.githubusercontent.com/assets/9932141/18201452/7dfaa2f4-710a-11e6-9612-cd3f59719816.png)

**Comment by kiswa** [comment] 2016-09-02 12:54
Can you show what comes up in the Response tab, instead of the headers?

**Comment by trephis** [comment] 2016-09-02 13:55
Oh I'm sorry. 
![bildschirmfoto vom 2016-09-02 15 51 46](https://cloud.githubusercontent.com/assets/9932141/18206109/88a4004a-7125-11e6-81f8-b6ea3dc155d7.png)

<html><head><title>Slim Application Error</title><style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style></head><body><h1>Slim Application Error</h1><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> ErrorException</div><div><strong>Code:</strong> 8</div><div><strong>Message:</strong> Trying to get property of non-object</div><div><strong>File:</strong> /var/www/html/TaskBoard/api/userRoutes.php</div><div><strong>Line:</strong> 7</div><h2>Trace</h2><pre><div>#0 /var/www/html/TaskBoard/api/userRoutes.php(7): Slim\Slim::handleErrors(8, 'Trying to get p...', '/var/www/html/T...', 7, Array)</div><div>#1 [internal function]: {closure}()</div><div>#2 /var/www/html/TaskBoard/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)</div><div>#3 /var/www/html/TaskBoard/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()</div><div>#4 /var/www/html/TaskBoard/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()</div><div>#5 /var/www/html/TaskBoard/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()</div><div>#6 /var/www/html/TaskBoard/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()</div><div>#7 /var/www/html/TaskBoard/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()</div><div>#8 /var/www/html/TaskBoard/api/api.php(52): Slim\Slim->run()</div><div>#9 {main}</pre></body></html>

**Comment by kiswa** [comment] 2016-09-02 19:01
That points to [this code](https://github.com/kiswa/TaskBoard/blob/master/api/userRoutes.php#L7), which means there's nothing coming to the API in the request.

Can you show what the request headers and body are? I see at least some of the request headers above, and they look fine.

**Comment by trephis** [comment] 2016-09-04 12:48
![bildschirmfoto vom 2016-09-04 14 43 14](https://cloud.githubusercontent.com/assets/9932141/18231080/8cb7518e-72ae-11e6-8221-f3c7632b7763.png)
![bildschirmfoto vom 2016-09-04 14 43 33](https://cloud.githubusercontent.com/assets/9932141/18231081/8f340024-72ae-11e6-8f16-10a68e1f3b0d.png)

**Comment by kiswa** [comment] 2016-09-09 15:25
Sorry about the delay in response. I have no idea what's going on here.

Have you had any luck with this since last week?

**Comment by trephis** [comment] 2016-09-16 06:45
Unfortunately not.

**Comment by kiswa** [comment] 2016-09-16 12:31
If you want to send me a message at [my Twitter](https://twitter.com/kiswa00/) with an external link to your setup, maybe I can figure something out?

**Comment by therealmaxmoon** [comment] 2016-09-19 16:56
Got a similar issue. Can't login to the server version, but the dev version (php -S 127.0.0.1:8080 devrouter.php) works fine. Any success yet?

**Comment by kiswa** [comment] 2016-09-19 17:17
Haven't heard anything yet. Out of curiosity, what PHP version?

**Comment by therealmaxmoon** [comment] 2016-09-19 17:19
`PHP 7.0.7 (cli) (built: May 25 2016 18:40:26) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
`

**Comment by therealmaxmoon** [comment] 2016-09-19 17:45
What are the differences between a http server and the php dev server? Does the php dev server load any modules a normal http server doesn't have?

**Comment by kiswa** [comment] 2016-09-19 18:45
Not sure why it would work with the dev server, but PHP 7 is not supported by the current TaskBoard. The `re-write` branch includes support for PHP 5.5.33 - PHP 7.x, but isn't in a functional state yet.

**Comment by therealmaxmoon** [comment] 2016-09-22 07:28
Could you give us a sign if the re-write branch is in a functional state, please. It would be awesome to use such a cool software on a private server.

**Comment by kiswa** [comment] 2016-09-22 15:29
It is not usable yet. :(

The API is complete, and the basics of all the front-end pages are in place, but the only active page (other than login) is Settings, and even that page is only 3/4ths complete.

I just realized I've been working on the re-write branch for 5 months! Hopefully, once Settings is done the rest will go faster (though the new Dashboard page will be interesting).

**Comment by trephis** [comment] 2016-09-25 17:30
@kiswa my username on twitter is trephis01

**Comment by kiswa** [comment] 2016-09-28 10:47
After going through the server, we determined the problem is with the dynamic DNS service in use.

**Closed by kiswa** 2016-09-28 10:47 UTC
