### ISSUE TITLE
No composer.json file under TaskBoard/build

### ISSUE THREAD

**Issue by saadismail** [kiswa/TaskBoard#223] opened 2015-10-10 05:38 UTC
There is no composer.json file under TaskBoard/build so 2nd step of installation with command "./composer.phar install" generates this error:
Composer could not find a composer.json file in /var/www/TaskBoard/build

In order to run this command successfully you need to copy /var/www/composer.json to /var/www/TaskBoard/build/composer.json

**Comment by MarioLiebisch** [comment] 2015-10-12 14:19
Had the same. Just install the latest version of "composer.phar" and run it from TaskBoard's root. Ignore the build directory.

**Comment by saadismail** [comment] 2015-10-12 16:13
I simply copied composer.json into build directory & that worked.

**Comment by kiswa** [comment] 2015-10-12 18:24
This is a duplicate of #222.

**Closed by kiswa** 2015-10-12 18:24 UTC
Labels: duplicate
