### ISSUE TITLE
Move task to different board

### ISSUE THREAD

**Issue by jniggemann** [kiswa/TaskBoard#172] opened 2015-04-23 13:50 UTC
I'd like to propose the following feature:

It would be nice it one could move a task to a different board.
I'd like to keep a separate "archive" board, containing all done tasks of the year to date.

**Comment by Dark-Fenix** [comment] 2015-05-12 09:29
+1 :)

**Comment by fuzzy76** [comment] 2015-05-22 18:53
IMHO, this is pretty crucial for doing scrum over time for larger projects. Typically you want to keep the backlog (all future tasks) in a separate board and create a new board for each sprint. When a sprint start, you move tasks from the backlog into the newly created sprint board.

**Comment by kiswa** [comment] 2016-02-09 15:10
Just realized this is a dupe of #107 which is scheduled for v0.4.0

**Closed by kiswa** 2016-02-09 15:10 UTC
Labels: enhancement
