### ISSUE TITLE
Login is lost after a few navigation changes

### ISSUE THREAD

**Issue by Philipp-IoT** [kiswa/TaskBoard#566] opened 2020-10-20 14:41 UTC
**Describe the bug**
The authorization is lost after a few clicks while browsing between Dashboard, Boards and Settings. Need to re-login after a few clicks. The error occurs with Vivaldi and Firefox borwsers. The Authorization header is not changed by the browser between the API requests.

Chromium Log:
`zone.js:3324 GET http://172.19.#.#/api/dashboard/tasks 401 (Unauthorized)`

Request Headers:
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,en-GB;q=0.6
Authorization: eyJ0*****lar4A
Connection: keep-alive
Content-Type: application/json
DNT: 1
Host: 172.19.65.6
Referer: http://172.19.#.#/dashboard
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.106 Safari/537.36

Response:
{status: "failure", data: [], alerts: [{type: "error", text: "Invalid API token."}]}
alerts: [{type: "error", text: "Invalid API token."}]
data: []
status: "failure"

**To reproduce**
1. Login
2. Change the navigation between Dashboard, Boards and Settings

**Expected behavior**
The login should not be lost after a few seconds of usage.

**Please complete the following information:**
- Server OS: Debian 10
- Apache Version: 2.4.38
- PHP Version: 7.3.19-1~deb10u1
- TaskBoard Version: 1.0.2

**Comment by c-louis** [comment] 2020-10-24 12:47
I currently have the exact same problem : 

Server OS : Archlinux
Apache Version : 2.4.46
PHP Version : 7.4.11
TaskBoard Version : 1.0.2

If you want to test it's currently setup on my vps : 

http://vps819233.ovh.net/tasks/

And if you want to see the php Configuration :

http://vps819233.ovh.net/test.php

**Comment by kiswa** [comment] 2020-10-27 15:13
Duplicate of #514

**Closed by kiswa** 2020-10-27 15:13 UTC
